
export const APP_TITLE = "台灣手語 (TSL) 影音辭典";
export const APP_SUBTITLE = "疾管署記者會手語翻譯檢索";
export const SEARCH_PLACEHOLDER = "輸入詞彙搜尋手語打法，例如：疫苗、隔離、快篩...";
export const NO_RESULTS_MESSAGE = "在疾管署的記者會存檔中找不到此詞彙，請嘗試其他關鍵字。";

// Playback settings
export const PRE_BUFFER_SECONDS = 2; // Start 2 seconds before to catch the start of the sign
export const DURATION_SECONDS = 10; // Loop duration

// Security: SHA-256 hash of '980415'
export const ADMIN_PASSWORD_HASH = "6dc7892f06b431afb325a0f9ccd94d0722f06c3da6551432172880abb17c68ef";

export const TRANSLATIONS = {
  zh: {
    title: "台灣手語 (TSL) 影音辭典",
    subtitle: "疾管署記者會手語翻譯檢索",
    source: "資料來源：疾管署",
    searchPlaceholder: "輸入詞彙搜尋手語打法，例如：疫苗、隔離、快篩...",
    searchButton: "搜尋",
    history: "最近搜尋",
    myVocabulary: "我的單字本",
    backToSearch: "返回搜尋",
    resultsFound: "找到 {count} 個手語片段",
    noResults: "在資料庫中找不到此詞彙，請嘗試其他關鍵字。",
    trySearching: "試試看搜尋「疫苗」？",
    commonTerms: "常查詞彙",
    medical: "醫療防疫",
    daily: "日常生活",
    all: "全部",
    loop: "循環播放",
    zoom: "放大畫面",
    speed: "速度",
    copyLink: "複製連結",
    copied: "已複製",
    playHere: "在此播放",
    showThumb: "顯示縮圖",
    watchOnYoutube: "去 YouTube 看",
    feedbackTitle: "意見回饋",
    feedbackDesc: "找不到想要的詞彙？或是發現翻譯有誤？歡迎告訴我們。",
    feedbackButton: "填寫回饋表單",
    footerDesc: "防疫小查詢 - 教育用途展示原型",
    bookmarked: "已收藏的單字片段",
    noBookmarks: "您目前沒有收藏任何片段。",
    noBookmarksHint: "在搜尋結果中點擊星星圖示即可收藏。",
    startFrom: "從 {time} 開始",
    adminLogin: "管理員登入",
    password: "密碼",
    login: "登入",
    logout: "登出",
    feedbackList: "回饋列表",
    noFeedbacks: "目前沒有回饋資料。",
    submit: "送出",
    cancel: "取消",
    feedbackType: "回饋類型",
    feedbackContent: "內容描述",
    successMsg: "發送成功！",
    newWord: "新增詞彙建議",
    bugReport: "錯誤回報",
    other: "其他"
  },
  en: {
    title: "TSL Video Dictionary",
    subtitle: "CDC Press Conference Sign Language Search",
    source: "Source: Taiwan CDC",
    searchPlaceholder: "Search vocabulary, e.g., Vaccine, Isolation...",
    searchButton: "Search",
    history: "Recent",
    myVocabulary: "My Vocabulary",
    backToSearch: "Back to Search",
    resultsFound: "Found {count} segments",
    noResults: "No segments found in the database. Please try other keywords.",
    trySearching: "Try searching for 'Vaccine'?",
    commonTerms: "Popular Terms",
    medical: "Medical/Epidemic",
    daily: "Daily Life",
    all: "All",
    loop: "Loop Segment",
    zoom: "Zoom",
    speed: "Speed",
    copyLink: "Share Link",
    copied: "Copied",
    playHere: "Play Here",
    showThumb: "Show Thumbnail",
    watchOnYoutube: "Watch on YouTube",
    feedbackTitle: "Feedback",
    feedbackDesc: "Can't find a word? Found an error? Let us know.",
    feedbackButton: "Fill Feedback Form",
    footerDesc: "TSL Search - Educational Prototype",
    bookmarked: "Bookmarked Segments",
    noBookmarks: "No bookmarks yet.",
    noBookmarksHint: "Click the star icon on any video to bookmark it.",
    startFrom: "Starts at {time}",
    adminLogin: "Admin Login",
    password: "Password",
    login: "Login",
    logout: "Logout",
    feedbackList: "Feedback List",
    noFeedbacks: "No feedbacks yet.",
    submit: "Submit",
    cancel: "Cancel",
    feedbackType: "Feedback Type",
    feedbackContent: "Description",
    successMsg: "Sent Successfully!",
    newWord: "New Word Suggestion",
    bugReport: "Bug Report",
    other: "Other"
  }
};
